name: Build & Release APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0' # Match your Flutter version
          channel: 'stable'

      # 3. Install dependencies
      - run: flutter pub get

      # 4. Extract version from pubspec.yaml
      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d"+" -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 5. Build release APK
      - run: flutter build apk --release

      # 6. Create GitHub Release & Upload APK
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: "Release v${{ steps.version.outputs.version }}"
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}